# Use a Node.js base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

RUN ls -R /app/src
# Build the TypeScript code
RUN npm run build

# Expose the port your application listens on (e.g., 3000)
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:prod"]
